### PR TITLE
introduction to flexdashboard and shiny

### PR DESCRIPTION
**Pull request by 0506Zhengyi**
introduction to flexdashboard and shiny
Yuezhu Xu and Zhengyi Fang

### CODE REVIEW

**Comment by 0506Zhengyi** [comment]
> Hi, please do the following:
> 
> * There should be no additional single hashtag headers in the chapter. (If there are, new chapters will be created.)

**Comment by jtr13** [comment]
@0506Zhengyi: It looks like you accidentally closed the PR -- I just reopened it.
@verlocks: can you review and merge if all looks good? Thanks.

**Comment by verlocks** [comment]
@jtr13 Is that ok there is a .Rmd file in the Resources folder? Or we should delete it? I read the main .Rmd file and there is no connection to this .Rmd file in the Resources folder so it should be fine to just delete it.
Other parts of it looks good to me, so once this settled, it should be able to be merged.

**Comment by 0506Zhengyi** [comment]
hi @verlocks, the Rmd.file includes the codes for creating the dashboard.
It is ok to delete it!

**Comment by verlocks** [comment]
@0506Zhengyi good, then I'll just delete it and merge the request. Thanks for your contribution!

**Pull request merged**
