### PR TITLE
Neo4j init submission

### PR DESCRIPTION
**Pull request by chaoyingzheng**

### CODE REVIEW

**Comment by mtz2110** [comment]
Hi, please make the following corrections:

1. All of the additional resources (not .Rmd file) should be in the resources/<project_name>/ folder.
2. The .Rmd filename can only contain lowercase letters. (Otherwise the filenames do not sort nicely on the repo home page.)
3. The file should not contain a YAML header nor a --- line.
4. The first line should start with a single hashtag #, followed by a single whitespace, and then the title.
5. The second line should be blank, followed by the author name(s).
6. Other hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings. Correct: ## Subheading. Incorrect: ## 3. Subheading.
7. The file should not contain any install.packages(), write functions, setwd(), or getwd(). (maybe put the install line as text instead of R code)

**Comment by chaoyingzheng** [comment]
Hi, all changes are made, please check. Thanks

**Comment by mtz2110** [comment]
Hi, thanks for making the changes.

One last thing; if you could change the following then it would all be good:

Change from:
# title: "From Neo4j to RStudio"

to:

# From Neo4j to RStudio

in line 1.

**Comment by mtz2110** [comment]
Hi, it seems that the file name changed back to the original name after this commit. Can you change it back with the following:

The .Rmd filename can only contain lowercase letters. (Otherwise the filenames do not sort nicely on the repo home page.)

**Comment by chaoyingzheng** [comment]
the file name is all lowercase on my local machine thought, not sure how to do that, any suggestion?

**Comment by mtz2110** [comment]
Great, thanks for your contribution!

**Comment by mtz2110** [comment]
@jtr13 Hi Dr. Robbins, just wanted to check in with you to review this pull request before merging!

**Comment by jtr13** [comment]
@mtz2110 Looks great! 🚀

**Comment by s10singh97** [comment]
@jtr13 Professor there is a problem with neo4j api and github actions. neo4j uses localhost with port 7474 which cannot be accessed by github actions in it's environment. There is a workaround to switch to neo4jshell but this would practically mean writing the complete code again. The build is failing because of this issue. Should we reopen the PR and request changes from the student? Or can we remove this from the _bookdown.yml file so that it does not get rendered for the time being so that other merges get reflected on the github pages successfully?

**Comment by jtr13** [comment]
Yes, let's do that and then discuss later how to handle. Sorry I missed that!

**Comment by jtr13** [comment]
I changed the approach to set `eval=FALSE` so that the chapter will still be included. See: https://github.com/jtr13/cc21fall1/issues/83

**Pull request merged**
