### PR TITLE
adding my file

### PR DESCRIPTION
**Pull request by ng4567**
Nikhil Gopal

### CODE REVIEW

**Comment by s10singh97** [comment]
There are multiple changes that needs to be made in order for this to conform to the submission instructions:
1. The file should not contain a YAML header nor a --- line.
2. The first line should start with a single hashtag #, followed by a single whitespace, and then the title.
3. The second line should be blank, followed by the author name(s).
4. There should be no additional single hashtag headers in the chapter. (If there are, new chapters will be created.)

**Comment by ng4567** [comment]
Hello Shashwat,

I have reformatted my .rmd file to comply with the instructions. Please review at your earliest convenience.

Nikhil

**Comment by s10singh97** [comment]
@ng4567 Please include the title as well in the first line in the format given below.
 -- The first line should start with a single hashtag #, followed by a single whitespace, and then the title.

Additionally, the name should be outside the R Chunk and the second line should be blank, followed by the author name(s).

**Comment by ng4567** [comment]
Hello Shashwat,

Apologies for the confusion, I have gone ahead and made the changes. Please review again.

Regards,
Nikhil

**Comment by s10singh97** [comment]
@ng4567 Can you modify the code so that it does not include `ggsave`? The build might fail because you are dynamically trying to save and load the file again.

**Comment by ng4567** [comment]
Shashwat,

I have not been able to find a way to save without this function. By "build" do you mean the knitting of the .RMD into an html file? I can remove the example code at the bottom so that the function is never called and then the file will knit (although it knits now).

I am also confused as to what you mean because every time I call ggsave I am using it on a different file, so I am not opening/closing the same file multiple times. 

Nikhil

**Comment by s10singh97** [comment]
@ng4567 So basically, since the github pages is built (we can say knit for time being) in a different environment. It will not allow to dynamically save or load any file. But if you have a static file from which you want to load data, it can put in this format (Links to internal files must contain `resources/<project_name>/`).

**Comment by s10singh97** [comment]
@ng4567 Also, since you are dynamically storing the plots in test and table documents, this operation is not allowed. It would be a better idea to show the plots in the Rmd itself rather than storing them in a file.

**Comment by jtr13** [comment]
Actually except for the last two lines, it's only since all the saving code is wrapped in a function. The problem with the last two lines when you call the function is that it is going to create the Word document in the GitHub repo where it's not accessible to anyone. I would recommend setting eval to FALSE and explaining that readers can run the code themselves to create the Word doc.

**Comment by ng4567** [comment]
I set the eval flag to false so that the code will not run, and removed the example code. I also added a README.txt file that explains that this was done to enable functionality with GitHub pages and gives a link to my GitHub repository for example code and further description of the package.

**Comment by s10singh97** [comment]
@ng4567 Please include the details mentioned in `README.txt` file in the Rmd file. As instructed in the submission guidelines [You should only submit ONE Rmd file](https://jtr13.github.io/cc21fall1/github-submission-instructions.html#preparing-your-.rmd-file).

**Comment by ng4567** [comment]
I have removed the .txt and added the explanation to the .RMD

**Comment by s10singh97** [comment]
Thank you for your contribution! 🎉

**Pull request merged**
