### PR TITLE
R for data challenges

### PR DESCRIPTION
**Pull request by wu000390**
Hi there, I still included a train.csv together with my Rmd file. I have code like "df<-read_csv('train.csv')" in my Rmd file, and I really don't know how to make it work if I put train.csv under /resources..

### CODE REVIEW

**Comment by mtz2110** [comment]
Hi, please make the following change:

1. All of the additional resources should be in the resources/<project_name>/ folder. (There should be no other files in the root directory besides the .Rmd file.)
2. Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings. Correct: ## Subheading. Incorrect: ## 3. Subheading.
3. Links to internal files must contain resources/<project_name>/ in the path, such as: Test Photo

You can replace the train.csv with the file path: resources/<project_name>/train.csv in the file.

**Comment by mtz2110** [comment]
@wu000390 please refer to the comment above for fixes to your submission. Thanks!

**Comment by wu000390** [comment]
Got it!

**Comment by mtz2110** [comment]
@wu000390 Yes! Thank you for your contribution.

**Pull request merged**
