### PR TITLE
Submission of github CC: Neo4j-GraphQL-cheatsheet.

### PR DESCRIPTION
**Pull request by oliverliuoo**

### CODE REVIEW

**Comment by ShiyuWang88** [comment]
Please submit a Rmd file instead of a pdf as the instruction said:

If your community contribution is in a different format, then create a short .Rmd file that explains what you did, and includes links to any relevant files, such as slides, etc. which you can post on your GitHub repo (or another online site.)

**Comment by oliverliuoo** [comment]
> Please submit a Rmd file instead of a pdf as the instruction said:
> 
> If your community contribution is in a different format, then create a short .Rmd file that explains what you did, and includes links to any relevant files, such as slides, etc. which you can post on your GitHub repo (or another online site.)

I have updated my pull request and put everything in a .Rmd file, thank you!

**Comment by ShiyuWang88** [comment]
Please have the following changes as the instruction said:

1. The .Rmd filename can only contain lowercase letters. (Otherwise the filenames do not sort nicely on the repo home page.)
2. The file should not contain a YAML header nor a --- line
3. The second line should be blank, followed by the author name(s).
4. If the file contains a setup chunk in .Rmd file, it should not contain a setup label. (The bookdown render will fail if there are duplicate chunk labels.) 
i.e. use {r, include=FALSE} instead of {r setup, include=FALSE}.

**Comment by ShiyuWang88** [comment]
Hi, Just kindly remind that you may need follow the above instructions to change your community contribution.

**Comment by ShiyuWang88** [comment]
Thanks for your community contribution! Congratulations 🎉

**Pull request merged**
