### PR TITLE
Add section for Data Science Product Cycles in Enterprises talk

### PR DESCRIPTION
**Pull request by leoDYL**
CC Group 1
Leo Du (yd2531) and Hao Li (hl3556)

### CODE REVIEW

**Comment by jtr13** [comment]
@ejosied @kfijan I added this to cheatsheets but maybe it belongs in a new talks section?

**Comment by kfijan** [comment]
@jtr13 @ejosied Yes, I think it should go in the Workshops section! It'll be the first one.

**Comment by kfijan** [comment]
@s10singh97 - is this ready to be merged?

**Comment by s10singh97** [comment]
@kfijan Yes! This is ready to be merged.

**Pull request merged**
