### PR TITLE
an3077 map reduce concept & comparision with R

### PR DESCRIPTION
**Pull request by anandwani**

### CODE REVIEW

**Comment by anandwani** [comment]
Please note,
1) I have added the comments with the links to Pdf, Html, and Recording in the top section
2) I have added my data in google drive and I am trying to access the data through that in the Rmd file. Hope that works. Let me know if there are any issues. thanks

**Review by clarissarjtai — CHANGES_REQUESTED** [review]
There should be no additional single hashtag headers in the chapter. (If there are, new chapters will be created.)
Other hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings. Correct: ## Subheading. Incorrect: ## 3. Subheading.
The file should not contain any install.packages(), write functions, setwd(), or getwd().
The .Rmd filename can only contain lowercase letters.

**Comment by anandwani** [comment]
1) Removed all single hashtag except the first one
2) Changed # 3) to ## 

Let me know if anything else needs to be changed or included. thanks

**Comment by ktsht** [comment]
Hello @clarissarjtai ,
It seems like mapreduce_concept_and_comparision_with_r.Rmd has some problem. Could you deal with this issue, please? Please check the GitHub Action No.147.

Here is a part of the error:
`Loading required package: grid
Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2
Quitting from lines 80-82 (mapreduce_concept_and_comparision_with_r.Rmd) 
Error: Error: Can't get Google credentials
ℹ Are you running googledrive in a non-interactive session? Consider:
• `drive_deauth()` to prevent the attempt to get credentials
• Call `drive_auth()` directly with all necessary specifics
ℹ See gargle's "Non-interactive auth" vignette for more details:
ℹ <https://gargle.r-lib.org/articles/non-interactive-auth.html>`

Thanks!

**Comment by ktsht** [comment]
@clarissarjtai 
OK, I commented out the mapreduce_concept_and_comparision_with_r.Rmd in the _bookdown.yml file so that the compiler won't read the file. And, it run successfully as you can see the GitHub Action #148 . So, once you guys resolve the issue of the mapreduce_concept_and_comparision_with_r.Rmd file, please remove the '#' in the _bookdown.yml.

Thank you!

**Comment by anandwani** [comment]
Hi @clarissarjtai 
Can you please try this once again? I tried enabling the apis for my google drive account through which I think any application will be able to access the public file.
If this doesn't work, then the next option is to generate a service token which we will have to store on the server, which will grant access to data over google drive.

**Comment by clarissarjtai** [comment]
@jtr13 I think here is some problem generated by the apis. Thank you

**Pull request merged**
