### PR TITLE
First revision of parallel coordinate plots in ggplot2

### PR DESCRIPTION
**Pull request by amruthasundar**

### CODE REVIEW

**Comment by verlocks** [comment]
@jtr13 hi professor, is it okay that the Rmd file uses '####' after '#' without '##' and '###'? I find that in [Regression and Classification in R](https://jtr13.github.io/cc21fall1/regression-and-classification-in-r.html) the numbered subheadings are like 8.0.1 because the file uses '###' instead of '##', and that may not be what we want here.

**Comment by jtr13** [comment]
@verlocks I agree, it's not ideal. Let's ask the authors not to use more than three hashtags.

**Comment by verlocks** [comment]
@amruthasundar Hi,
please use two hashtags ## instead of four hashtags ####, and three hashtags ### instead of five hashtags #####.
The online book will automatedly create numbered subheadings based on the number of hashtags, and using four hashtags #### at the beginning will create the subheading like x.0.0.1 rather than x.1.

**Comment by verlocks** [comment]
Thanks for your contribution!

**Pull request merged**
