### PR TITLE
supervised_learning_tutorial.Rmd

### PR DESCRIPTION
**Pull request by sw3049**
community contribution

### CODE REVIEW

**Comment by Ivanye2509** [comment]
Thank you so much for your contribution!

**Comment by Ivanye2509** [comment]
@ShiyuWang88 Hi Shiyu, would you reviewing this PR before I merge it since I didn't find any problems for this one. Thank you so much!

**Comment by s10singh97** [comment]
@Ivanye2509 Looks good to me! Please proceed with the merge. Before merging just check whether their bookdown file has the latest changes in them

**Comment by ShiyuWang88** [comment]
@Ivanye2509 I think this one looks good.

**Comment by Ivanye2509** [comment]
@s10singh97 @ShiyuWang88 Thank you for the review!

**Pull request merged**
