### PR TITLE
Add rmd_syntax_cheatsheet.Rmd

### PR DESCRIPTION
**Pull request by Yufancao**
Common Rmd syntax cheatsheet

### CODE REVIEW

**Comment by Ivanye2509** [comment]
Please do the following changes:
1. Change the subheadings in line 11, 13, 28, etc, because "Other hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings. Correct: ## Subheading. Incorrect: ## 3. Subheading."

**Comment by s10singh97** [comment]
@Ivanye2509 Looks good to me! Please update their `_bookdown.yml` file before merging.

**Comment by Ivanye2509** [comment]
@Yufancao Thank you so much for your contribution! 
@s10singh97 Thank you for your review!

**Comment by kfijan** [comment]
There is a single # in this file causing issues with the bookdown, "# Header". @s10singh97 @Ivanye2509

**Comment by s10singh97** [comment]
@kfijan Yeah I will rectify this

**Comment by Ivanye2509** [comment]
@kfijan Sorry for the mistake, I didn't see that single hashtag before when reviewing this .rmd file!

**Comment by Ivanye2509** [comment]
@kfijan Should I revert the merge and ask the author to revise it? Thank you!

**Pull request merged**
