### PR TITLE
Icons and symbols in r

### PR DESCRIPTION
**Pull request by celiajin**
add "wmpeople1.TTF" to resources

### CODE REVIEW

**Comment by Ivanye2509** [comment]
@jtr13  Hi, Professor Robbins, Would you mind checking this since there are two commits and I am not sure if I am doing it right? Thank you!

Please do the following change:
1. There should be only ONE .Rmd file in the files changed section instead of five.

**Comment by jtr13** [comment]
There's only one .Rmd file but there are three .DS_Store files which should be deleted. You can either delete them or ask the PR author to do so.

**Comment by celiajin** [comment]
> @jtr13 Hi, Professor Robbins, Would you mind checking this since there are two commits and I am not sure if I am doing it right? Thank you!
> 
> Please do the following change:
> 
> 1. There should be only ONE .Rmd file in the files changed section instead of five.


Got the .DS_Store files deleted.

**Comment by jtr13** [comment]
Looks good to me. It's ok to have multiple commits. In fact each time there's an edit to one of the files in the pull request, there will be another commit.

**Comment by Ivanye2509** [comment]
@jtr13 Thank you for your review!
@celiajin Please also delete the .TTF file in the files changes section as well, thank you!

**Comment by s10singh97** [comment]
@Ivanye2509 Sorry to bug in but I believe that .TTF file is fine. This is an external file which is being used in their code on line [84](https://github.com/celiajin/cc21fall1/blob/icons_and_symbols_in_r/icons_and_symbols_in_r.Rmd#L84) and is correctly placed inside the resources folder as per the [submission guidelines](https://jtr13.github.io/cc21fall1/github-submission-instructions.html#submission-steps) -- (bullet 6).

Thanks!

**Comment by jtr13** [comment]
It looks like this PR is a duplicate of https://github.com/jtr13/cc21fall1/pull/24 which was already merged.

**Comment by celiajin** [comment]
I got this feedback after PR#24 being merged "can you open a new pull request and add the wmpeople1.TTF file in this format: Links to internal files must contain resources/<project_name>/ in the path. Thanks!"

**Comment by jtr13** [comment]
Ok, now I understand! @s10singh97 can you review this and let @Ivanye2509 if it's ready to be merged?

**Comment by Ivanye2509** [comment]
@celiajin Thank you for your contribution and sorry for the confusion!
@s10singh97 Thank you for pointing that mistake out!
@jtr13 Thank you for checking this out again!

**Pull request merged**
