### PR TITLE
Analyse awss3 r

### PR DESCRIPTION
**Pull request by kiranvrpk**
Analyze data stored in AWS S3 using R 

Kiranmai Vasireddy(pv2342)

This post walks you through how data stored in an AWS s3 bucket can be accessed from RStudio and further analysed.

### CODE REVIEW

**Review by ktsht — CHANGES_REQUESTED** [review]
Hello, thanks for the submission. One minor thing. Could you remove .DS_Store file from your PR because it has to only contain one .Rmd file?

The instruction follows:
> There should be no other files in the root directory besides the .Rmd file.

**Comment by jtr13** [comment]
@ktsht  Is this ready to merge now?

**Comment by ktsht** [comment]
@jtr13 Yes -- and I will merge it.

**Comment by ktsht** [comment]
@jtr13 It is now deployed successfully! Thanks for the contribution @kiranvrpk !

**Pull request merged**
