### PR TITLE
Community Contribution Group 6

### PR DESCRIPTION
**Pull request by gzmason**

### CODE REVIEW

**Comment by ShiyuWang88** [comment]
Please follow the below rules as said in the instructions:
1. The .Rmd filename can only contain lowercase letters. (Otherwise the filenames do not sort nicely on the repo home page.)
2. The first line should start with a single hashtag #, followed by a single whitespace, and then the title.
3. The second line should be blank, followed by the author name(s).

**Comment by ShiyuWang88** [comment]
@jtr13 Hi, Dr.Joyce:
This one do have include resources/ in the file path to link to internal files but it has multiply links to the resources, I'd like to double check if this is appropriate?

**Comment by jtr13** [comment]
It's ok to have multiple image files (as they do) but the `.zip` file is problematic. Those files should be in a separate repo with a link provided here to that repo.

**Comment by gzmason** [comment]
I changed the rmd file, deleted the zip file and made a new repo. Could you check again?

**Comment by ShiyuWang88** [comment]
@jtr13 Hi, Dr.Joyce, Thanks for your reply. I have another question that whether it is fine to have capital letters in the branch name and the link to the resources?

**Comment by jtr13** [comment]
Yes, that's fine. We're only concerned about the chapter file names so they sort nicely in the root directory of the repo.

**Comment by ShiyuWang88** [comment]
@ejosied Hi, I see this community contribution has been labeled "Demonstration", I'd like to ask if there is supposed to be the a Demonstration part in our main bookdown yml since I have not find one in the main bookdown yml? Or should I attribute it to the Tutorial?

**Comment by ejosied** [comment]
@ShiyuWang88 Hi Shiyu, I have added the section to the bookdown file. Thanks for the reminder!
Josie

**Pull request merged**
