### PR TITLE
Create 30_questions_answers_for_r_interview.Rmd

### PR DESCRIPTION
**Pull request by Anna1027**

### CODE REVIEW

**Comment by aye21874** [comment]
Hi!
The second line should be blank, followed by the author's name(s).

**Comment by Anna1027** [comment]
Hi,
I just put a space on the second line! Thank you!

**Comment by s10singh97** [comment]
@aye21874 Please do the following before merging.

Instead of removing all the names from _bookdown.yml, copy the latest version of _bookdown.yml from the main branch of our project (it will contain the updated and the latest version of the _bookdown.yml file) and paste it into the submitted repo's _bookdown.yml file and at the end you can add the name of the new .Rmd file. In this way there would be no conflicts and we can just merge it directly.
Alternatively, once you have copied the main branch bookdown.yml file in the student's branch and added their file name, you can mark it for review and I can review it.

---- In case of any confusion (before merging), please tag me and I will look into it.

Thanks!

**Comment by aye21874** [comment]
Thank you for your contribution!

**Comment by aye21874** [comment]
You can find your contribution showcased here:
https://jtr13.github.io/cc21fall1/questions-answers-for-r-technical-interview.html

**Pull request merged**
